name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
preparacion_entorno:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

  - name: npm install
    run: npm install

  - name: lint
    run: npm run eslint
  
  - name: test
    run: npm run test